#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
terminal_background = 'p:t-background'
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:terminal-blue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:light-sky-blue'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ .Behind }} {{ end }}{{ if gt .Ahead 0 }}⇡{{ .Ahead }} {{ end }}</>'

    [blocks.segments.properties]
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 1000

  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    foreground = 'p:pistachio-green'
    template = ' {{ .Full }} '

  # TODO: need to fix this
  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    foreground = 'p:terminal-yellow'
    template = ' {{ .Full }} '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      '{{if gt .Code 0}}terminal-red{{end}}',
      '{{if eq .Code 0}}terminal-magenta{{end}}',
    ]
    background = 'transparent'
    template = '❯'

[[tooltips]]
type = 'aws'
tips = ['aws', 'terraform']
style = 'plain'
foreground = 'p:terminal-yellow'
template = '󰸏 {{.Profile}}{{if .Region}}@{{.Region}}{{end}}'

[[tooltips]]
type = "az"
tips = ['az', 'terraform']
style = 'plain'
foreground = 'p:celeste-blue'
template = '  {{ .Name }}'

[secondary_prompt]
  foreground = 'terminal-magenta'
  background = 'transparent'
  template = '❯❯ '

[palette]
  main-bg = '#24283b'
  terminal-red = '#f7768e'
  pistachio-green = '#9ece6a'
  terminal-green = '#73daca'
  terminal-yellow = '#e0af68'
  terminal-blue = '#7aa2f7'
  celeste-blue = '#b4f9f8'
  light-sky-blue = '#7dcfff'
  terminal-white = '#c0caf5'
  white-blue = '#a9b1d6'
  blue-bell = '#9aa5ce'
  pastal-grey = '#cfc9c2'
  terminal-magenta = '#bb9af7'
  blue-black = '#565f89'
  terminal-black = '#414868'
  t-background = 'p:main-bg'
